# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    user: 1000:1000
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./.docker/nginx/logs:/var/log/nginx/
    ports:
      - 3300:3300
    depends_on:
      - app